### ISSUE TITLE
Plugin will not work

### ISSUE THREAD

**Issue by DFO627** [kyza-betterdiscord/ShowAllMessageButtons#13]
So I tried installing the plugin, but this error shows up:

**Error:** 

ENOENT: no such file or directory, lstat 'C:\Users\(Username)\AppData\Local\Discord\app-1.0.9037\url'
    at Object.realpathSync (betterdiscord/renderer.js:5:370182)
    at p.getFilePath (betterdiscord/renderer.js:5:371881)
    at p._load (betterdiscord/renderer.js:5:371976)
    at betterdiscord/renderer.js:5:375069
    at eval (betterdiscord://plugins/ShowAllMessageButtons.plugin.js:133:39)
    at eval (betterdiscord://plugins/ShowAllMessageButtons.plugin.js:391:3)
    at N.requireAddon (betterdiscord/renderer.js:5:28792)
    at N.loadAddon (betterdiscord/renderer.js:5:6412)
    at N.loadAddon (betterdiscord/renderer.js:5:26460)
    at AsyncFunction.<anonymous> (betterdiscord/renderer.js:5:4392)

**Comment by Ryuktheshinigamix** [comment]
been dead for over a year now
