### ISSUE TITLE
Show all message buttons Couldn't be compiled 

### ISSUE THREAD

**Issue by RedixWasTaken** [kyza-betterdiscord/ShowAllMessageButtons#9]
TypeError: Cannot destructure property 'publishMessage' of 'PublishButton_findModuleByProps(...)' as it is undefined.
2	at eval (betterdiscord://plugins/ShowAllMessageButtons.plugin.js:98:3)
3	at eval (betterdiscord://plugins/ShowAllMessageButtons.plugin.js:391:3)
4	at Object.requireAddon (<anonymous>:4:39192)
5	at Object.loadAddon (<anonymous>:4:9163)
6	at Object.loadAddon (<anonymous>:4:36864)
7	at Object.loadAllAddons (<anonymous>:4:11637)
8	at Object.initialize (<anonymous>:4:6059)
9	at Object.initialize (<anonymous>:4:36059)
10	at Object.startup (<anonymous>:4:396505)

**Comment by Ryuktheshinigamix** [comment]
Same thing bruh been like this for ages. Plugin just hasnt been updated so everythings broken i guess.
